// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD73kkzOe-YnLUZxgTWgNad_mlt2CuunA',
    appId: '1:264070742144:web:65b2d991a7de2fcb782665',
    messagingSenderId: '264070742144',
    projectId: 'loginfirebaseflutter-1033a',
    authDomain: 'loginfirebaseflutter-1033a.firebaseapp.com',
    storageBucket: 'loginfirebaseflutter-1033a.firebasestorage.app',
    measurementId: 'G-SFPGMDRHB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqK174eojpT3JrWYrkj7zylx6TedjBolM',
    appId: '1:264070742144:android:797dec8ae747fc1b782665',
    messagingSenderId: '264070742144',
    projectId: 'loginfirebaseflutter-1033a',
    storageBucket: 'loginfirebaseflutter-1033a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAawIUmsWdwAnUn_RObkeDAA8_ZBoT6mow',
    appId: '1:264070742144:ios:394ef56cd84f8d83782665',
    messagingSenderId: '264070742144',
    projectId: 'loginfirebaseflutter-1033a',
    storageBucket: 'loginfirebaseflutter-1033a.firebasestorage.app',
    iosClientId: '264070742144-5pmn0e5fee35rnq11lnmsdaeod1tor8j.apps.googleusercontent.com',
    iosBundleId: 'com.example.start',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAawIUmsWdwAnUn_RObkeDAA8_ZBoT6mow',
    appId: '1:264070742144:ios:394ef56cd84f8d83782665',
    messagingSenderId: '264070742144',
    projectId: 'loginfirebaseflutter-1033a',
    storageBucket: 'loginfirebaseflutter-1033a.firebasestorage.app',
    iosClientId: '264070742144-5pmn0e5fee35rnq11lnmsdaeod1tor8j.apps.googleusercontent.com',
    iosBundleId: 'com.example.start',
  );
}
